package web

import (
	"embed"
	"io/fs"
	"net/http"
)

// Embed static files
//
//go:embed static/*
var staticFiles embed.FS

// Template files are generated by templ, no need to embed HTML files

// GetStaticFS returns the embedded static files as an http.FileSystem
func GetStaticFS() http.FileSystem {
	fsys, err := fs.Sub(staticFiles, "static")
	if err != nil {
		panic(err)
	}
	return http.FS(fsys)
}

// GetTemplateFS is not needed since we use templ generated templates
func GetTemplateFS() fs.FS {
	return nil
}

// StaticHandler returns an http.Handler for serving static files
func StaticHandler() http.Handler {
	return http.FileServer(GetStaticFS())
}

// AssetExists checks if a static asset exists
func AssetExists(name string) bool {
	_, err := staticFiles.Open("static/" + name)
	return err == nil
}

// GetAsset returns the content of a static asset
func GetAsset(name string) ([]byte, error) {
	return staticFiles.ReadFile("static/" + name)
}
